export default {
    alignContent: {
        "0": "auto",
        "1": "flexStart",
        "2": "center",
        "3": "flexEnd",
        "4": "stretch",
        "5": "baseline",
        "6": "spaceBetween",
        "7": "spaceAround",
        "8": "count",
    },
    alignItems: {
        "0": "auto",
        "1": "flexStart",
        "2": "center",
        "3": "flexEnd",
        "4": "stretch",
        "5": "baseline",
        "6": "spaceBetween",
        "7": "spaceAround",
        "8": "count",
    },
    alignSelf: {
        "0": "auto",
        "1": "flexStart",
        "2": "center",
        "3": "flexEnd",
        "4": "stretch",
        "5": "baseline",
        "6": "spaceBetween",
        "7": "spaceAround",
        "8": "count",
    },
    display: { "0": "flex", "1": "none", "2": "count" },
    flexDirection: { "0": "column", "1": "columnReverse", "2": "row", "3": "rowReverse", "4": "count" },
    flexWrap: { "0": "noWrap", "1": "wrap", "2": "wrapReverse", "3": "count" },
    justifyContent: {
        "0": "flexStart",
        "1": "center",
        "2": "flexEnd",
        "3": "spaceBetween",
        "4": "spaceAround",
        "5": "spaceEvenly",
        "6": "count",
    },
    overflow: { "0": "visible", "1": "hidden", "2": "scroll", "3": "count" },
    positionType: { "0": "relative", "1": "absolute", "2": "count" },
}
