export default {
    positionType: "relative",
    alignContent: "flexStart",
    alignItems: "stretch",
    alignSelf: "auto",
    flexDirection: "column",
    flexWrap: "noWrap",
    justifyContent: "flexStart",
    flexGrow: 0,
    flexShrink: 0,
    width: "auto",
    height: "auto",
    overflow: "visible",
    display: "flex",
}
